name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to Heroku
        env:
          HEROKU_REGISTRY_URL: registry.heroku.com
          HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
        run: |
          docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
          export HEROKU_API_KEY=$HEOKU_TOKEN
          heroku container:login
          heroku container:push web --app coursepage
          heroku container:release web --app coursepage
          heroku ps:scale web=1 coursepage
